### ISSUE TITLE
Fix eth api errors

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/auction#34]
When trying to run the auction backend I see the following error. 

```
{"name":"validator-auction-backend-server","hostname":"bernd-ThinkPad-T480s","pid":17787,"class":"api","level":50,"err":{"message":"Cannot read property 'value.hex' of undefined","name":"TypeError","stack":"TypeError: Cannot read property 'value.hex' of undefined\n    at allEvents.filter.map.e (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:206:69)\n    at Array.map (<anonymous>)\n    at EthEventsClient.getWhitelistedAddresses (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:205:72)\n    at EthEventsClient.getAuctionSummary (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:41:43)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)"},"msg":"Cannot read property 'value.hex' of undefined","time":"2020-05-19T15:47:31.451Z","v":0}
{"name":"validator-auction-backend-server","hostname":"bernd-ThinkPad-T480s","pid":17787,"class":"controller","level":50,"msg":"Unexpected error: TypeError: Cannot read property 'value.hex' of undefined\n    at allEvents.filter.map.e (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:206:69)\n    at Array.map (<anonymous>)\n    at EthEventsClient.getWhitelistedAddresses (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:205:72)\n    at EthEventsClient.getAuctionSummary (/home/bernd/programming/trustlines/auction/lib/EthEventsClient.js:41:43)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)","time":"2020-05-19T15:47:41.458Z","v":0}
{
```

**Comment by berndbohmeier** [comment]
Whith further debugging, it showed that the event looks different:
```
...
{ args:
   [ { 'value.hex': '0x0e229662d303610431BDD7C26910409D58ae5aF2',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x830ec74739925853F1Fad8b45f5B572F2EC5fd2F',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x7B785e072b02f1226c59D1EAB191D447F8377308',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x2713AeDAEB2B5DbBF6F8C22350155557693d788d',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x4e34347c5Cb4450CD142a4f2167B7754f4423110',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x62654BC2D5cdf72bFC6997a43A936F4db849D245',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x3110e1fe01De0B86395cA343E19589c0b2b567C9',
       name: 'whitelistedAddress',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
{ args:
   [ { 'value.hex': '0x1dA37d5322ACb2B09962cF48D37CF09CC83C98dA',
       name: 'address_',
       'value.type': 'address',
       pos: 0 } ],
  event: 'AddressWhitelisted' }
```
The last has `address_` for unknown reason.

**Comment by berndbohmeier** [comment]
The reason was that the abi was not stored for that specific contract and so it will use known contracts but random
